#ifndef RENDER_MODES_HPP
#define RENDER_MODES_HPP

enum RenderMode
{
	NORMAL_MODE,
	DEFERRED_MODE,
	DEFERRED_CHUNK_MODE,
	DEFERRED_SPLIT_MODE,
	DEFERRED_MULTIPLE_LIGHTS_MODE,
	DEFERRED_MULTIPLE_SHADOW_LIGHTS_MODE,
	DEPTH_MODE,
	NR_OF_RENDER_MODES
};

#endif